// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/expenses": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/api/auth": {
    params: {};
  };
  "/api/auth/callback": {
    params: {};
  };
  "/api/fetch-orders": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/expenses" | "/privacy" | "/terms" | "/api/auth" | "/api/auth/callback" | "/api/fetch-orders";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/expenses.tsx": {
    id: "routes/expenses";
    page: "/expenses";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/api.auth.ts": {
    id: "routes/api.auth";
    page: "/api/auth";
  };
  "routes/api.auth.callback.ts": {
    id: "routes/api.auth.callback";
    page: "/api/auth/callback";
  };
  "routes/api.fetch-orders.ts": {
    id: "routes/api.fetch-orders";
    page: "/api/fetch-orders";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/expenses": typeof import("./app/routes/expenses.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/api.auth": typeof import("./app/routes/api.auth.ts");
  "routes/api.auth.callback": typeof import("./app/routes/api.auth.callback.ts");
  "routes/api.fetch-orders": typeof import("./app/routes/api.fetch-orders.ts");
};